# Generated by Django 2.2 on 2019-04-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20190410_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='ident',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='id'),
        ),
    ]
